---
title: "My Dollar Is My Identity: How Moral Priming of Women and Men Affects Charitable Donations"
author: "Divya Ramachandran and Louis J. Zmich "
date: "04/15/2020"
output: html_document
---
Americans have consistently demonstrated generosity with regard to charitable donations. In fact, the United States ranks in the top five nations for giving to charities, collecting close to $300 billion in 2018. However, this constitutes around 2% of the United States’ disposable income, a rather small percentage that has been a consistent limit to U.S. donations for over 40 years. Why does this 2% giving cap exist? What factors are at play here? These questions are significant when we consider that not-for-profits are one of the most important agencies in solving social problems such as poverty, inequality, and pollution at a global level. Our society is rife with not-for-profits that are determined to make a difference in the world but are heavily reliant on their donors. Although not-for-profits take advantage of donation days and various other charitable drives that occur throughout the year, and see higher donations in times of natural disasters, they still struggle with the 2% giving cap. The impact of the current COVID situation on the global society underscores the importance of understanding the drivers of giving behavior and donations and breaking through this giving ceiling.

When someone gives to a good cause, their identity almost becomes tied to that mission. For instance, people donating to a clean water campaign might label themselves environmental activists, while people donating to an inequality campaign may consider themselves humanitarians. But in these two examples, does it matter whether a man or a woman donated to these campaigns? Does gender influence the dollar amounts donated? Shang and colleagues’ recently published research addresses these critical questions with regard to charitable donations by positioning their research between the pillars of moral identity, gender, and the role of giving behavior in reducing moral identity discrepancy (the gap between actual and ideal moral identity). The authors’ finding that women (but not men) who are primed with moral traits give approximately 20% more to charitable causes, suggesting gender differences in supporting a not-for-profit mission. Specifically, giving campaigns that shrink this gap between actual and ideal moral identity (in women) can receive more generous donations than campaigns that simply ask for donations.

We reached out to the authors to understand their motivations behind this unique study and to explore their findings in greater detail. We were curious to understand how the authors pinpointed the moral identity between men and women as being the focal point behind the study. The authors, fundamentally, were inspired by classic evolutionary theories of social agency that suggest different motivational drivers for men vs. women to interact with the world around them. For instance, women in traditional “roles” have been socialized over time and rewarded as caretakers and nurturers in their family roles. Research has found that these roles create a tendency to be more “collective.” On the other hand, men tend to be rewarded for their social capital linked to power and wealth creation, and studies show that this relates to a tendency to be more “individualistic.”[1] This led the authors to wonder whether these differences might potentially lead women and men to respond differently to external triggers and the possible impact on their giving behaviors. The authors were also interested in whether women and men would be differentially sensitive to a moral prime that would invoke thoughts related to kindness, compassion, caring, etc. Furthermore, they wondered if this difference would lead to different experiences among women vs. men with regard to their moral image vs. desired ideal moral image (moral discrepancy). Finally, the authors wanted to examine the impact of this moral discrepancy in terms of marketplace donation behavior and philanthropic giving.

We delved further into gender differences between the giving tendencies of men and women. In the experiments conducted by the authors, donors were thanked for their donation with words of affirmation, like “kind” and “caring.” We wondered whether men were subconsciously averse to this language when describing their actions, such that they might instinctively “swat the hand” that pats them on the head for doing a good job, whereas women view those words of affirmation as encouraging words that reaffirm their groundedness in society. The authors clarified that this “swatting away,” if you will, is not out of stigma, and it may just be that men are not “tuned” to that kind of feedback in the same way women are. Thus, women do not respond in the same way. While the authors do not claim that men do not give, or will not give under other circumstances, they simply explored the differences that may be invoked as a function of exposure to certain cues that may trigger thoughts about kindness, caring, compassion, etc. The authors wanted to see if the difference between how one sees one’s moral image compared to one’s ideal moral image may change as a function of giving, and how that giving may reinforce their identity differently as a function of gender.

When the authors began to uncover the reasons why men and women differ in their giving tendencies, we thought it was wise to discuss related questions for subsequent authors who are looking to research in this area. First, we wanted to know if there might be other underlying mechanisms (apart from encouragement and upliftment) of giving behavior, for instance, social image or social impressions. The authors stressed that additional mechanisms could have to do with personal pride, or what researchers might refer to as an emotion of morality that one may experience. The authors were particularly interested in the concept of “warm glow” (feeling good about yourself because you know that you did something good) and emphasized how giving may solidify one’s status in society. For instance, people may perceive strong philanthropic givers as “established” and there may be external praise heaped upon the giver. While these are just a few possible reasons that can be explored in future research, they may also reveal robust differences in how the genders experience differential giving as a function of external and internal cues.

Second, from a methodological perspective, we wondered how the authors approached the moral identity discrepancy scale development measures. Specifically, we were interested to understand the detailed process required to develop the moral identity discrepancy scale, as well as possible challenges that researchers might encounter in this regard. The authors emphasized that while they were proud of their article in taking baby steps towards a preliminary moral discrepancy measure, more psychometric work needs to be done to develop the scale and ascertain its statistical properties. Although, there is always concern with “social desirability” when asking a person to introspect on how they see themselves as a moral being, the authors believed that the idea of measuring any identity discrepancy (where there may be internal and external factors that shrink and expand such a gap) is indeed a logical next step in research on identity more generally, and more specifically, in research in the moral domain. At the end of the day, the authors felt that the development of a scale would become an empirical question. The authors believed that a scale having robust properties would predict things in a logical and systematic fashion, in much the same way that the moral identity scale by Aquino and Reed (2002) has proven to be able to do.

In the context of donation behavior and philanthropic giving, it was difficult not to touch on the COVID-19 situation, and how that affects businesses around the world, especially not-for-profits who rely on donations to function. The article indicated that a shift in marketing to potential donors was undoubtedly necessary, and we wanted the authors’ views on whether this 2% donation cap can be solved mainly through a shift in marketing tone, for instance, centered around benefiting society at large, benefiting the community in which we operate? Furthermore, it seemed to us like donations go through ups and downs, shifting depending on the world’s events, and time of year. But we wondered whether a mentality shift, where people in our society began to look at charity giving as another monthly budget item that benefited the community they reside in, might create a more significant positive effect for both men and women.

The authors felt that these were interesting potential implications of their research, with the global COVID-19 pandemic possibly leading to very interesting shifts in market donations and giving patterns. The authors felt that this could work both ways. People viewing the global threat as a trigger might choose to give more and more often outside their close circle of moral regard. People could also view this situation in the opposite way, whereby this threat to the common good could trigger a need to protect those that are closest to them and that are most vulnerable in their inner circle. The authors believe that there are probably lots of different moderators at play, including many of the ones studied in their article. According to the authors, marketing tone will play a key role in influencing giving behavior, but so will the way in which the benefactor of the donation is framed to the potential donor.

[1] We thought it important to clarify the authors’ position here: “We are not saying that men cannot be kind, caring, giving, nurturing, etc., but it is a matter of degree and the external things that trigger potential different amounts of giving for men vs. women might be different.”


Full Article

Shang, Jen, Americus Reed, Adrian Sargeant, and Kathryn Carpenter. “Marketplace Donations: The Role of Moral Identity Discrepancy and Gender.” Journal of Marketing Research 57, no. 2 (April 2020): 375–93.
